# Configuration file for cargo-deny

[graph]
targets = [
    # Targets used by zcashd
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "x86_64-unknown-freebsd" },
    { triple = "x86_64-unknown-linux-gnu" },
    # Targets used by zcash-android-wallet-sdk
    { triple = "aarch64-linux-android" },
    { triple = "armv7-linux-androideabi" },
    { triple = "i686-linux-android" },
    { triple = "x86_64-linux-android" },
    # Targets used by zcash-swift-wallet-sdk
    { triple = "aarch64-apple-darwin" },
    { triple = "aarch64-apple-ios" },
    { triple = "aarch64-apple-ios-sim" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-apple-ios" },
]
all-features = true
exclude-dev = true

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
]
exceptions = [
    { name = "arrayref", allow = ["BSD-2-Clause"] },
    { name = "async_executors", allow = ["Unlicense"] },
    { name = "aws-lc-rs", allow = ["ISC", "OpenSSL"] },
    { name = "aws-lc-sys", allow = ["ISC", "OpenSSL"] },
    { name = "bindgen", allow = ["BSD-3-Clause"] },
    { name = "bounded-vec", allow = ["CC0-1.0"] },
    { name = "bounded-vec-deque", allow = ["BSD-3-Clause"] },
    { name = "coarsetime", allow = ["ISC"] },
    { name = "curve25519-dalek", allow = ["BSD-3-Clause"] },
    { name = "ed25519-dalek", allow = ["BSD-3-Clause"] },
    { name = "inotify", allow = ["ISC"] },
    { name = "inotify-sys", allow = ["ISC"] },
    { name = "libloading", allow = ["ISC"] },
    { name = "minreq", allow = ["ISC"] },
    { name = "notify", allow = ["CC0-1.0"] },
    { name = "option-ext", allow = ["MPL-2.0"] },
    { name = "priority-queue", allow = ["MPL-2.0"] },
    { name = "rdrand", allow = ["ISC"] },
    { name = "ring", allow = ["ISC", "LicenseRef-ring"] },
    { name = "rustls-webpki", allow = ["ISC"] },
    { name = "secp256k1", allow = ["CC0-1.0"] },
    { name = "secp256k1-sys", allow = ["CC0-1.0"] },
    { name = "slotmap", allow = ["Zlib"] },
    { name = "subtle", allow = ["BSD-3-Clause"] },
    { name = "tinystr", allow = ["Unicode-3.0"] },
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
    { name = "untrusted", allow = ["ISC"] },
    { name = "webpki-roots", allow = ["CDLA-Permissive-2.0", "MPL-2.0"] },
    { name = "x25519-dalek", allow = ["BSD-3-Clause"] },
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
