//! Conformance tests against the ZIP 221 / ZIP 229 chain history MMR test
//! vectors published by `zcash-test-vectors`.
//!
//! The vector modules below are generated by an independent reimplementation of
//! the specification (`zcash_test_vectors/zip_0221.py`), so checking this crate
//! against them is a genuine cross-validation rather than a self-consistency
//! check. For each tree version the vectors walk a deterministic 16-leaf tree,
//! recording, per tree size, the appended leaf's inputs together with the
//! serialized peaks, serialized root node, and `hashChainHistoryRoot`.

mod zip_0221_v1;
mod zip_0221_v2;
mod zip_0221_v3;

use primitive_types::U256;

use crate::{Entry, NodeData, NodeDataV2, NodeDataV3, Tree, V1, V2, V3, Version};

/// Builds the V1 (Sapling) leaf metadata for a single block.
///
/// A leaf spans a single block, so every earliest/latest pair collapses to that
/// block's single value.
// A block leaf is built from eight independent header/metadata values; bundling
// them into a struct would not make the conversion any clearer.
#[allow(clippy::too_many_arguments)]
fn sapling_leaf(
    consensus_branch_id: u32,
    block_hash: [u8; 32],
    time: u32,
    target_bits: u32,
    sapling_root: [u8; 32],
    work: [u8; 32],
    height: u64,
    sapling_tx: u64,
) -> NodeData {
    NodeData {
        consensus_branch_id,
        subtree_commitment: block_hash,
        start_time: time,
        end_time: time,
        start_target: target_bits,
        end_target: target_bits,
        start_sapling_root: sapling_root,
        end_sapling_root: sapling_root,
        subtree_total_work: U256::from_little_endian(&work),
        start_height: height,
        end_height: height,
        sapling_tx,
    }
}

/// Appends `leaf` to `tree` (initializing it on the first leaf) and asserts the
/// resulting state matches the test vector for this tree size.
fn check_leaf<V>(
    tree: &mut Option<Tree<V>>,
    leaf: V::NodeData,
    n_leaves: u32,
    leaf_serialized: &[u8],
    peaks: &[&[u8]],
    root_serialized: &[u8],
    hash_chain_history_root: [u8; 32],
) where
    V: Version,
    V::NodeData: PartialEq + core::fmt::Debug,
{
    // The leaf metadata serializes to the spec bytes and round-trips. The
    // consensus branch ID is not part of the serialization; on read it is
    // supplied out of band, here recovered from the leaf itself.
    let consensus_branch_id = V::consensus_branch_id(&leaf);
    assert_eq!(V::to_bytes(&leaf).as_slice(), leaf_serialized);
    assert_eq!(
        V::from_bytes(consensus_branch_id, leaf_serialized).expect("leaf should deserialize"),
        leaf
    );

    // Append the leaf, initializing the tree from the first leaf.
    match tree {
        None => *tree = Some(Tree::new(1, vec![(0, Entry::new_leaf(leaf))], Vec::new())),
        Some(tree) => {
            tree.append_leaf(leaf).expect("append should succeed");
        }
    }
    let tree = tree.as_ref().expect("tree was initialized above");

    // The root spans the expected number of leaves and commits to the same
    // serialization and `hashChainHistoryRoot` as the spec.
    let root = tree.root_node().expect("root should be resolvable");
    assert_eq!(root.node().leaf_count(), u64::from(n_leaves));
    assert_eq!(V::to_bytes(root.data()).as_slice(), root_serialized);
    assert_eq!(V::hash(root.data()), hash_chain_history_root);

    // The peaks enumerate left-to-right and serialize to the expected bytes.
    let mut peak_links = Vec::new();
    tree.get_peaks(tree.root(), &mut peak_links)
        .expect("peaks should be resolvable");
    assert_eq!(peak_links.len(), peaks.len());
    for (link, expected) in peak_links.iter().zip(peaks) {
        let peak = tree.resolve_link(*link).expect("peak should be resolvable");
        assert_eq!(V::to_bytes(peak.data()).as_slice(), *expected);
    }
}

#[test]
fn zip_0221_v1_chain_history() {
    let mut tree: Option<Tree<V1>> = None;
    for tv in zip_0221_v1::TEST_VECTORS {
        let leaf = sapling_leaf(
            tv.consensus_branch_id,
            tv.leaf_block_hash,
            tv.leaf_time,
            tv.leaf_target_bits,
            tv.leaf_sapling_root,
            tv.leaf_work,
            tv.leaf_height,
            tv.leaf_sapling_tx_count,
        );
        check_leaf::<V1>(
            &mut tree,
            leaf,
            tv.n_leaves,
            tv.leaf_serialized,
            tv.peaks,
            tv.root_serialized,
            tv.hash_chain_history_root,
        );
    }
}

#[test]
fn zip_0221_v2_chain_history() {
    let mut tree: Option<Tree<V2>> = None;
    for tv in zip_0221_v2::TEST_VECTORS {
        let leaf = NodeDataV2 {
            v1: sapling_leaf(
                tv.consensus_branch_id,
                tv.leaf_block_hash,
                tv.leaf_time,
                tv.leaf_target_bits,
                tv.leaf_sapling_root,
                tv.leaf_work,
                tv.leaf_height,
                tv.leaf_sapling_tx_count,
            ),
            start_orchard_root: tv.leaf_orchard_root,
            end_orchard_root: tv.leaf_orchard_root,
            orchard_tx: tv.leaf_orchard_tx_count,
        };
        check_leaf::<V2>(
            &mut tree,
            leaf,
            tv.n_leaves,
            tv.leaf_serialized,
            tv.peaks,
            tv.root_serialized,
            tv.hash_chain_history_root,
        );
    }
}

#[test]
fn zip_0221_v3_chain_history() {
    let mut tree: Option<Tree<V3>> = None;
    for tv in zip_0221_v3::TEST_VECTORS {
        let leaf = NodeDataV3 {
            v2: NodeDataV2 {
                v1: sapling_leaf(
                    tv.consensus_branch_id,
                    tv.leaf_block_hash,
                    tv.leaf_time,
                    tv.leaf_target_bits,
                    tv.leaf_sapling_root,
                    tv.leaf_work,
                    tv.leaf_height,
                    tv.leaf_sapling_tx_count,
                ),
                start_orchard_root: tv.leaf_orchard_root,
                end_orchard_root: tv.leaf_orchard_root,
                orchard_tx: tv.leaf_orchard_tx_count,
            },
            start_ironwood_root: tv.leaf_ironwood_root,
            end_ironwood_root: tv.leaf_ironwood_root,
            ironwood_tx: tv.leaf_ironwood_tx_count,
        };
        check_leaf::<V3>(
            &mut tree,
            leaf,
            tv.n_leaves,
            tv.leaf_serialized,
            tv.peaks,
            tv.root_serialized,
            tv.hash_chain_history_root,
        );
    }
}
