[package]
name = "pairing"

# Remember to change version string in README.md.
version = "0.16.0"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <jack@z.cash>",
]
readme = "README.md"
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/ebfull/pairing"
repository = "https://github.com/ebfull/pairing"
edition ="2018"

[dependencies]
byteorder = "1"
ff = { version = "0.6", path = "../ff", features = ["derive"] }
group = { version = "0.6", path = "../group" }
rand_core = "0.5"
subtle = "2.2.1"

[dev-dependencies]
criterion = "0.3"
rand_xorshift = "0.2"

[features]
unstable-features = ["expose-arith"]
expose-arith = []
default = []

[[bench]]
name = "pairing_benches"
harness = false

[badges]
maintenance = { status = "actively-developed" }
