//! Any and all errors encountered during parsing and validation.

use snafu::prelude::*;

use crate::parse::Value;

/// Errors discovered during parsing.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub(crate)))]
#[non_exhaustive]
pub enum ParseError<'a> {
    /// A parsing error generated by `nom`.
    #[snafu(display("{}", nom::error::Error::to_string(&nom::error::Error {
        input: *input, code: *code
    })))]
    Nom {
        input: &'a str,
        code: nom::error::ErrorKind,
        other: Option<String>,
    },

    /// The number of digits did not match or exceed the expected minimum.
    #[snafu(display(
        "Expected at least {min} digits, saw {digits_len} before {}",
        input.split_at(10).0
    ))]
    DigitsMinimum {
        min: usize,
        digits_len: usize,
        input: &'a str,
    },

    /// The character is not a hexadecimal digit.
    #[snafu(display("The character '{character}' was expected to be hexadecimal, but isn't."))]
    NotAHexDigit { character: char },

    /// The ENS name was expected and missing.
    #[snafu(display("Missing ENS name"))]
    EnsMissing,

    /// The ENS name was not a valid domain.
    #[snafu(display("Not a domain"))]
    EnsDomain,

    /// The ENS name could not be normalized.
    #[snafu(display("{source}"))]
    EnsNormalization {
        source: ens_normalize_rs::ProcessError,
    },

    /// The ENS should be normalized, but wasn't.
    #[snafu(display("ENS name must be normalized. Expected '{expected}' but saw '{seen}'"))]
    NotNormalized { expected: String, seen: String },

    /// A parameter value had an unexpected value.
    #[snafu(display("Invalid parameter value. Expected a {ty}."))]
    InvalidParameterValue { ty: String },

    /// A parameter key had an unexpected value.
    #[snafu(display("Invalid parameter key '{key}'."))]
    InvalidParameterKey { key: String },

    /// Unexpected leftover input after parsing.
    #[snafu(display("Unexpected leftover input: {input}"))]
    UnexpectedLeftoverInput { input: &'a str },

    /// A [`Number`] candidate had no mantissa digits (no integer digits and no
    /// decimal part), and so does not represent the `number` alternative of
    /// the `value` grammar production.
    ///
    /// [`Number`]: crate::parse::Number
    #[snafu(display("Number candidate has no mantissa digits at: {input}"))]
    NumberMissingDigits { input: &'a str },
}

impl<'a> nom::error::ParseError<&'a str> for ParseError<'a> {
    fn from_error_kind(input: &'a str, code: nom::error::ErrorKind) -> Self {
        NomSnafu {
            input,
            code,
            other: None,
        }
        .build()
    }

    fn append(input: &'a str, code: nom::error::ErrorKind, other: Self) -> Self {
        NomSnafu {
            input,
            code,
            other: Some(other.to_string()),
        }
        .build()
    }
}

impl<'a> From<ParseError<'a>> for nom::Err<ParseError<'a>> {
    fn from(value: ParseError<'a>) -> Self {
        nom::Err::Error(value)
    }
}

/// All the reasons an ERC-55 check-summed address might fail validation.
#[derive(Debug, PartialEq)]
#[non_exhaustive]
pub enum Erc55ValidationFailureReason {
    /// The input failed validation, but is all lowercase, and may not have been check-summed.
    AllLowercase,
    /// The input failed validation, but is all upper, and may not have been check-summed.
    AllUppercase,
    /// The input failed validation.
    ChecksumDoesNotMatch { expected: String, saw: String },
}

/// Errors discovered after parsing, usually when attempting to convert parsed
/// types into numeric types.
#[derive(Debug, Snafu, PartialEq)]
#[non_exhaustive]
#[snafu(visibility(pub(crate)))]
pub enum ValidationError {
    #[snafu(display(
        "Incorrect number of digits for an ethereum address. Expected 40, saw {len}."
    ))]
    IncorrectEthAddressLen { len: usize },

    #[snafu(display("Exponent is too small, expected at least {expected}, saw {seen}"))]
    SmallExponent { expected: usize, seen: u64 },

    #[snafu(display("Exponent is too large, expected at most {expected}, saw {seen}"))]
    LargeExponent { expected: usize, seen: u64 },

    #[snafu(display(
        "Arithmetic operation resulted in an overflow, exceeding the allowable range"
    ))]
    Overflow,

    #[snafu(display("Cannot convert negative number to unsigned type"))]
    NegativeValueForUnsignedType,

    #[snafu(display("Could not decode url-encoded string: {source}"))]
    UrlEncoding { source: std::str::Utf8Error },

    /// An attempt to convert an integer failed.
    #[snafu(display("Integer conversion failed: {source}"))]
    Integer { source: std::num::TryFromIntError },

    /// More than one value exists in a parameter list with a key
    /// that denotes a single value.
    #[snafu(display(
        "More than one parameter by the key '{key}', saw: [{}]",
        values.iter().map(|(k, v)| format!("{k}={v}")).collect::<Vec<_>>().join(", ")
    ))]
    MultipleParameterValues {
        key: &'static str,
        values: Vec<(&'static str, Value)>,
    },

    /// An Ethereum address failed ERC-55 checksum validation.
    #[snafu(display("ERC-55 checksum validation failure: {reason:?}"))]
    Erc55Validation {
        reason: Erc55ValidationFailureReason,
    },
}

/// Errors encountered while converting [`RawTransactionRequest`] into
/// [`Erc20Request`].
///
/// [`RawTransactionRequest`]: crate::parse::RawTransactionRequest
/// [`Erc20Request`]: crate::Erc20Request
#[derive(Debug, Snafu)]
#[non_exhaustive]
#[snafu(visibility(pub(crate)))]
pub enum Erc20Error {
    #[snafu(display("Transaction is missing the function name"))]
    MissingFn,

    #[snafu(display("Expected function name to be 'transfer', saw '{seen}'"))]
    FnName { seen: String },

    #[snafu(display("Incorrect number of ABI parameters, expected 2, saw '{seen}'"))]
    AbiParameterLen { seen: usize },

    #[snafu(display(
        r#"Incorrect ABI parameter names, \
        expected "address" and "uint256" - saw "{param1}" and "{param2}""#
    ))]
    AbiParameterName { param1: String, param2: String },

    #[snafu(display("The 'address' parameter value is not an address"))]
    AbiParameterAddressIsNotAnAddress,

    #[snafu(display("The 'uint256' parameter is not a number"))]
    AbiParameterUint256,

    #[snafu(display("The 'uint256' parameter could not be converted: {source}"))]
    AbiParameterUint256Conversion { source: std::num::TryFromIntError },
}

/// Errors encountered while converting [`RawTransactionRequest`] into [`NativeRequest`].
///
/// [`RawTransactionRequest`]: crate::parse::RawTransactionRequest
/// [`NativeRequest`]: crate::NativeRequest
#[derive(Debug, Snafu)]
#[non_exhaustive]
#[snafu(visibility(pub(crate)))]
pub enum NativeTransferError {
    #[snafu(display("Has a function name"))]
    HasFunctionName,

    #[snafu(display("Request has ABI parameters"))]
    HasAbiParameters,

    #[snafu(display("Parameter '{key}' is not a number"))]
    ParameterNotNumber { key: String },

    #[snafu(display("Parameter '{key}' value is invalid: {source}"))]
    ParameterInvalid {
        key: String,
        source: ValidationError,
    },

    #[snafu(display("Invalid chain ID: {source}"))]
    ChainIdInvalid { source: ValidationError },

    #[snafu(display("Invalid recipient address: {source}"))]
    RecipientAddressInvalid { source: ValidationError },
}

/// Top-level errors for the transaction request API.
#[derive(Debug, Snafu)]
#[snafu(visibility(pub(crate)))]
#[non_exhaustive]
pub enum Error {
    /// An error occurred during parsing.
    #[snafu(display("Parsing error: {message}"))]
    Parse { message: String },

    /// An error occurred during validation.
    #[snafu(display("Validation error: {source}"))]
    Validation { source: ValidationError },

    /// The provided address string is not a valid Ethereum address.
    #[snafu(display("Invalid Ethereum address: {address}"))]
    InvalidAddress { address: String },

    /// The request is not a valid ERC-20 transfer.
    #[snafu(display("Not an ERC-20 transfer request: {source}"))]
    NotErc20Transfer { source: Erc20Error },

    /// The request is not a valid native transfer.
    #[snafu(display("Not a native transfer request: {source}"))]
    NotNativeTransfer { source: NativeTransferError },
}

impl From<ValidationError> for Error {
    fn from(source: ValidationError) -> Self {
        Error::Validation { source }
    }
}

impl From<Erc20Error> for Error {
    fn from(source: Erc20Error) -> Self {
        Error::NotErc20Transfer { source }
    }
}

impl From<NativeTransferError> for Error {
    fn from(source: NativeTransferError) -> Self {
        Error::NotNativeTransfer { source }
    }
}

impl From<ParseError<'_>> for Error {
    fn from(value: ParseError<'_>) -> Self {
        Error::Parse {
            message: value.to_string(),
        }
    }
}

impl<'a> From<nom::Err<ParseError<'a>>> for Error {
    fn from(value: nom::Err<ParseError<'a>>) -> Self {
        Error::Parse {
            message: value.to_string(),
        }
    }
}
