name: 'Prepare CI'
description: 'Prepares feature flags'
inputs:
  extra-features:
    description: 'Extra feature flags to enable'
    required: false
    default: ''
  transparent-pool:
    description: 'Enable all transparent pool-specific feature flags'
    required: false
    default: false
  orchard-pool:
    description: 'Enable all Orchard pool-specific feature flags'
    required: false
    default: false
  all-pools:
    description: 'Enable all pool-specific feature flags'
    required: false
    default: true
  all-features:
    description: 'Enable all feature flags'
    required: false
    default: false
  test-dependencies:
    description: 'Include test dependencies'
    required: false
    default: true
outputs:
  feature-list:
    description: 'Space-separated feature names, empty when all features are enabled'
    value: ${{ steps.prepare.outputs.features }}
  all-features:
    description: 'Whether all features are enabled'
    value: ${{ inputs.all-features }}
runs:
  using: 'composite'
  steps:
    - id: transparent-pool
      shell: bash
      run: echo "features=transparent-inputs transparent-key-import transparent-key-encoding" >> $GITHUB_OUTPUT
      if: inputs.transparent-pool == 'true' || inputs.all-pools == 'true'

    - id: orchard-pool
      shell: bash
      run: echo "features=orchard" >> $GITHUB_OUTPUT
      if: inputs.orchard-pool == 'true' || inputs.all-pools == 'true'

    - id: test
      shell: bash
      run: echo "feature=test-dependencies" >> $GITHUB_OUTPUT
      if: inputs.test-dependencies == 'true'

    - name: Prepare feature flags
      id: prepare
      shell: bash
      run: |
        read -ra extra_features <<< "$EXTRA_FEATURES"
        read -ra transparent_features <<< "$TRANSPARENT_FEATURES"
        read -ra orchard_features <<< "$ORCHARD_FEATURES"
        read -ra test_features <<< "$TEST_FEATURES"
        features=(
          bundled-prover
          download-params
          lightwalletd-tonic
          sync
          temporary-zcashd
          unstable
          unstable-serialization
          unstable-spanning-tree
          "${extra_features[@]}"
          "${transparent_features[@]}"
          "${orchard_features[@]}"
          "${test_features[@]}"
        )
        echo "features=${features[*]}" >> "$GITHUB_OUTPUT"
      env:
        EXTRA_FEATURES: ${{ inputs.extra-features }}
        ORCHARD_FEATURES: ${{ steps.orchard-pool.outputs.features }}
        TEST_FEATURES: ${{ steps.test.outputs.feature }}
        TRANSPARENT_FEATURES: ${{ steps.transparent-pool.outputs.features }}
      if: inputs.all-features == 'false'
